### PR TITLE
Mimic classic notebook behavior for /tree/<path>

### PR DESCRIPTION
**Pull request by yuvipanda**
- Show directory listing if path is a directory
- Show notebook if path is a notebook
- Return file contents if path is any other file

Copied from https://github.com/jupyter/notebook/blob/6fe9755971dba3357054766806d56cb8c6c1bca7/notebook/tree/handlers.py#L39

Fixes https://github.com/jupyterlab/retrolab/issues/153

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> Show directory listing if path is a directory

For this to properly work we'll probably need https://github.com/jupyterlab/retrolab/issues/15.

**Comment by yuvipanda** [comment]
@jtpio yep! It currently just shows base tree view.

**Comment by jtpio** [comment]
@meeseeksdev please backport to 0.2.x

**Pull request merged**
