### PR TITLE
Route on file browser navigation

### LINKED ISSUE #15: Route on file browser navigation
At the moment there is no routing when navigating in the file browser:

filebrowser-no-routing

Also we should be able to restore the file browser on page load, for example opening the `binder` folder when http://localhost:8888/classic/tree/binder is accessed.

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #15

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Does this also handle updating the URL when navigating folders, like in the classic notebook?

https://user-images.githubusercontent.com/591645/131683675-703bdbd1-184f-48ce-9e94-6020ab27c557.mp4

**Comment by fcollonval** [comment]
I'm unsure the error is relevant as it happens only on Chromium. Did you encounter random failure in the past?

**Comment by jtpio** [comment]
> I'm unsure the error is relevant as it happens only on Chromium. Did you encounter random failure in the past?

Not yet. Will restart the check to be sure.

**Comment by jtpio** [comment]
Thanks for the update. Looks like it's almost ready to go.

When checking on Binder the base url gets appended once on first navigation:

https://user-images.githubusercontent.com/591645/131701935-403c91e9-66df-450b-8752-683aed686782.mp4

**Review by jtpio — APPROVED** [review]
Thanks!!

**Comment by jtpio** [comment]
Will cut `0.3.3` with this and https://github.com/jupyterlab/retrolab/pull/203

**Comment by jtpio** [comment]
`0.3.3` is out: https://pypi.org/project/retrolab/0.3.3/

**Pull request merged**
