### PR TITLE
Lowercase string for translation

### LINKED ISSUE #238: store translatable string in normal case
## Description

This was raised by a translator on Crowdin

String: "RETROLAB ON GITHUB"
Tunghsiao Liu (sparanoid):
It's better to store string in normal case and stylize it using CSS `text-transform: uppercase`.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #238

### CODE REVIEW

**Comment by jtpio** [comment]
cc @fcollonval

**Review by fcollonval — APPROVED** [review]
LGTM

do you want to keep the upper case by setting CSS style?

**Comment by krassowski** [comment]
It is not immediately obvious to me if we should add a CSS rule. It is not as bad as with "capitalize" (see discussion in https://stackoverflow.com/questions/21050401/css-text-transform-capitalize-and-italian-spanish-portuguese-french-etc and https://stackoverflow.com/questions/46320915/will-css-text-transform-uppercase-and-capitalize-work-on-any-language-without-c) but I can imagine some languages having different semantics for all-caps, or having fonts making those less readable. My original intention was to leave it to translators to decide what lettercase they prefer.

**Comment by jtpio** [comment]
Thanks @krassowski for the input.

> My original intention was to leave it to translators to decide what lettercase they prefer.

Fine for me either way especially if it helps translators. However the comment reported by @fcollonval in https://github.com/jupyterlab/retrolab/issues/238 suggest some translators might have different opinions.

I pushed the `text-transform: uppercase` fix. If we decide to go that way, maybe we should also update these in the JupyterLab help extension?

https://github.com/jupyterlab/jupyterlab/blob/723a17677006a7c4bff313e93466e35956d347aa/packages/help-extension/src/index.tsx#L117-L134

**Comment by krassowski** [comment]
I still stand by my opinion that it's better to leave letter case handling to the translators, and while I cannot find a normative text for it, there are others who think so: [here](https://github.com/meetup/sassquatch2/issues/144#issuecomment-118958029), [here](https://gili842.medium.com/dont-use-transform-text-here-s-why-4d7ac7c804da), [here](https://github.com/vuetifyjs/vuetify/issues/10693) and even [Localization at Mozilla - Internal Documentation: Localization best practices for developers](https://mozilla-l10n.github.io/documentation/localization/dev_best_practices.html#css-issues):

> CSS issues
> 
> Some CSS text/font properties may cause problems with text legibility when applied to certain scripts. For example, avoid using Italic for CJK locales — Chinese (Simplified and Traditional), Japanese, and Korean.
> 
> The text-transform property is not reliable for some locales; for example, text-transform: uppercase won’t work with languages such as Irish/Gaelic or Turkish (İi vs Iı). App Size in English may be capitalized via text-transform: uppercase to APP SIZE but in Gaelic this would change Meud na h-aplacaid to MEUD NA H-APLACAID, which violates the locales orthographic rules, as it ought to be MEUD NA hAPLACAID. In some cases, it can even lead to a different meaning. Consider the following examples in Irish:
> 
>     Athair = Father
>     Nathair = Snake
>     Ár nAthair = Our Father
>     Ár Nathair = Our Snake
>     ÁR NATHAIR = OUR SNAKE
>     ÁR nATHAIR = OUR FATHER
> 
> In general, localizers should make the decision about capitalization. If you want to display WARNING uppercase, add a string directly with that capitalization, and explain it in the localization note. This is particularly important for web content, where the CSS implementation depends on the browser in use. Even within Firefox, the correct behavior depends on having the correct lang attribute associated to the text or document.


I highly value sparanoid's contributions to the translation project, but I do not agree with their opinion on this one. The Gaelic and Irish examples cited above make it clear that we should not use `text-transform: uppercase`

**Comment by jtpio** [comment]
Thanks @krassowski for the details, this is really helpful :+1: 

Happy to close this PR and #238 and leave the string as is in uppercase.

**Comment by jtpio** [comment]
Closing based on the discussion above.

**Pull request closed without merging**
