### PR TITLE
Add support for translation

### LINKED ISSUE #27: Support for translation
### TODO

- [x] Replace the placeholder translator to enable translation

https://github.com/jtpio/jupyterlab-classic/blob/0b4ddce87dd320a3699b2ad2b467db215bffbc82/packages/application-extension/src/index.ts#L362-L373

- [x] Use the translator for user facing strings

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #27 

image

### CODE REVIEW

**Review by goanpeca — COMMENTED** [review]
🚀

**Comment by goanpeca** [comment]
Pinging @fcollonval and @krassowski 

How should we go about incorporating the strings  in retrolab in the current i18n workflow 🤔

**Comment by jtpio** [comment]
Binder now includes the French language pack so it's easier to test:

image

**Comment by fcollonval** [comment]
> How should we go about incorporating the strings in retrolab in the current i18n workflow thinking

I would recommend treating `retrolab` as an any extension. Therefore I would suggest updating this PR by using a new domain for the translation and not the base `jupyterlab` one. If we don't go that path and use `jupyterlab` as i18n domain, we will have a hard time to deal with the few strings that are only related to `retrolab`.

**Comment by jtpio** [comment]
> using a new domain for the translation and not the base `jupyterlab` one

RetroLab defines a set of custom plugins just like what a normal extension would do, so it makes sense to use a different domain yes.

**Comment by jtpio** [comment]
https://github.com/jupyterlab/retrolab/pull/229/commits/edc96c17cfd426d83c0f3cfe7ce1b57cdfbb1948 switched to using a custom domain. So this should be good to go now.

cc @goanpeca @fcollonval @krassowski if you want to have a look and merge

**Review by fcollonval — APPROVED** [review]
LGTM

**Comment by goanpeca** [comment]
Agreed! as an extension indeed, would be the easiest :) , 

Thanks for the PR and the updates. LGTM!

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
