### PR TITLE
Update to JupyterLab 3.1.0-beta.0 packages

### PR DESCRIPTION
**Pull request by jtpio**
Update to the latest JupyterLab `3.1.0-alpha.13` packages.

Replaces https://github.com/jupyterlab/retrolab/pull/154

### CODE REVIEW

**Comment by jtpio** [comment]
Ah the new menu system via settings seems to be breaking at runtime: 

image

**Comment by jtpio** [comment]
cc @fcollonval looks like this could be a breaking change in 3.1?

**Comment by jtpio** [comment]
Or I guess we need to be able to load the default menu items from upstream JupyterLab?

Or the `MenuFactory` should also be able to work without that default list.

**Comment by jtpio** [comment]
Ah never mind that, it might just be an issue with packages being mixed up locally.

**Comment by fcollonval** [comment]
Let me know, if there is still a problem with the new menu system. It should be corrected if it is indeed not backward compatible.

**Comment by jtpio** [comment]
I think the issue was that the frontend `@jupyterlab` packages were on the latest `3.1.0-alpha.13`, with the Python package still on `3.1.0a8`, which means it was not serving the `mainmenu-extension` plugin settings with the menus.

**Comment by fcollonval** [comment]
Thanks for the details

**Comment by jtpio** [comment]
Looks like switching from `jest` to `@playwright/test` fixing the end to end tests. As a side-effect this makes the test code cleaner.

**Comment by jtpio** [comment]
Tests now passing, and looking good on Binder so we should be able to go ahead and merge this.

**Pull request merged**
