### PR TITLE
Fix handling of federated mime extensions

### LINKED ISSUE #258: JupyterLab extensions that only operate within a notebook do not all work in RetroLab
## Description
I understand that some JupyterLab extensions that access non-notebook areas in JupyterLab are not yet expected to work in RetroLab. However, something is inconsistent about the way RetroLab handles JupyterLab extensions that operate only within a notebook without modifying anything in the other Jupyterlab areas. Extensions/widgets this is known to impact: `plotly`

## Reproduce
1. `pip install plotly numpy pandas` into the environment of JupyterLab/RetroLab.
2. In a new notebook create a simple data set to plot.
```
import pandas as pd
import numpy as np
X = [k*np.pi/10 for k in range(-30,30)]
Y = np.sin(X)
df = pd.DataFrame({'X':X, 'Y':Y})
df['size']=df['X']/3/np.pi
```
3. Plot it.
```
from plotly import graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=df["X"], y=df['Y'],mode='lines+markers',name='sin(x)'))
fig.add_trace(go.Scatter(x=df["X"], y=df['size'],mode='lines',name='y = x')) 
fig.update_layout(template='simple_white')
fig.update_xaxes(mirror='ticks')
fig.update_yaxes(mirror=True)
fig.show()
```
This works in an .ipynb running in JupyterLab but in RetroLab nothing is displayed.

## Expected behavior
Expect the same graph displayed in JupyterLab and RetroLab

## Context

- Operating System and version: Linux Ubuntu 20.04
- Browser and version: FireFox 93.0 or Chromium 95.0.4638.54  
- JupyterLab version: RetroLab 0.3.11

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #258 

image

To test on Binder:

```
pip install plotly
```

Reload the page. Then:

```python
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()
```

### CODE REVIEW

**Comment by jtpio** [comment]
Looks good on Binder:

image

**Comment by gutow** [comment]
Although this is merged into the main repo when I launch the main repo in binder, I still get blank images RetroLab, but it works in JupyterLab. I imported the latest plotly into the binder instance. Did follow on commits break this?

**Comment by gutow** [comment]
I think I found the problem. The binder link does not point to the latest version of this repo, but a different repo. I will create a different issue.

**Comment by jtpio** [comment]
FYI @gutow `0.3.12` has been released with this fix: https://github.com/jupyterlab/retrolab/releases/tag/v0.3.12

**Comment by gutow** [comment]
great

**Pull request merged**
