### PR TITLE
Enable auto scrolling for outputs by default

### LINKED ISSUE #287: Automatically scroll output area with large text outputs
### Problem

When printing output that is a large amount of text, there is currently no output scrolling. This means users have to scroll quite far to get to the next code block.

image

Compared with classic notebook, which automatically scrolls by default

image

(images courtesy @davidwagner from https://github.com/berkeley-dsep-infra/datahub/issues/2992)

### Proposed Solution

In https://github.com/jupyterlab/jupyterlab/issues/4028, a setting was added to JupyteLab to enable this behavior. But it isn't on by default (IIRC). In retrolab, we should turn this on by default!

### Additional context

Am trying to get the large [data8](https://data8.org) class at Berkeley switch from classic notebook to retrolab, and this is part of a series of issues we're trying to tackle before it can be rolled out to total newbie students.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #287 

https://user-images.githubusercontent.com/591645/147688295-071f2436-d47a-41e8-9db4-c9b06f97be6b.mp4

### TODO

- [x] Replicate the classic notebook logic: https://github.com/jupyter/notebook/blob/a9a31c096eeffe1bff4e9164c6a0442e0e13cdb3/notebook/static/notebook/js/outputarea.js#L96-L120
- [x] Add UI Test
- [x] Open issue / PR to upstream in JupyterLab
  - https://github.com/jupyterlab/jupyterlab/issues/5897
  - https://github.com/jupyterlab/jupyterlab/issues/11760

cc @yuvipanda

### CODE REVIEW

**Comment by jtpio** [comment]
Converting to draft for now.

We should check the logic in the classic notebook to handle the auto scrolling.

With the naive logic as it is now in this PR this would enable it even for small outputs:

image

**Comment by yuvipanda** [comment]
Trying to match classic makes sense here. I think we should eventually upstream this into lab, but this is a great place to try this out. Thanks a lot for looking into this, @jtpio

**Comment by jtpio** [comment]
There is some logic in the `_should_scroll` function here:

https://github.com/jupyter/notebook/blob/a9a31c096eeffe1bff4e9164c6a0442e0e13cdb3/notebook/static/notebook/js/outputarea.js#L96-L120

**Comment by jtpio** [comment]
A follow-up to this would be to update to JupyterLab 3.2.5 packages to grab https://github.com/jupyterlab/jupyterlab/pull/11478

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/jupyterlab/issues/11760 to track that upstream.

**Comment by jtpio** [comment]
cc @yuvipanda if you want to give it a try on Binder: https://mybinder.org/v2/gh/jtpio/retrolab/scroll-outputs?urlpath=retro/tree

I'll do a bit more testing but if it works fine we can merge and release.

Thinking we might also want to make it possible to disable that behavior via the settings system (opt-out).

**Comment by jtpio** [comment]
> Thinking we might also want to make it possible to disable that behavior via the settings system (opt-out).

Implemented in https://github.com/jupyterlab/retrolab/pull/288/commits/84df24d25ac1abf515d46d7fd4bbae7ae5a453c9

**Comment by jtpio** [comment]
Did some more testing on Binder and it seems to be working fine.

Will make a new release with this change after merging.

**Pull request merged**
