### PR TITLE
Add support for code consoles

### LINKED ISSUE #49: Support for code consoles
It should be possible to reuse the existing `console-extension` from JupyterLab.

Then consoles could be available via the `/classic/consoles/1` endpoint like terminals.

The main question is whether we want to add them to JupyterLab Classic (with the trade-off of making the interface too complicated).

Code consoles in JupyterLab:

image

### LINKED ISSUE #104: Unused context menu entries "Create New View for Output" / "New Console for Notebook"
When I right-click inside a cell, I get two entries in the context menu, that don't perform any function as far as I can tell:

- Create New View for Output
- New Console for Notebook

No real issue, but I guess it could be confusing to new users.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #49 
Fixes #104

Something that does not exist in the classic notebook by default, but is nice to have as a very minimalist web based code prompt on a single page.

Also related to https://github.com/jupyterlite/jupyterlite/issues/148

image

image

### TODO

- [x] Add package scaffolding
- [x] Add new handler and template
- [x] Add to the file browser menu
- [x] Fix console creation flow

### CODE REVIEW

**Comment by bollwyvl** [comment]
Sooo.... you going to have any way to link this to an editor?

**Comment by jtpio** [comment]
> Sooo.... you going to have any way to link this to an editor?

You mean a text editor like the screenshot in [this comment](https://github.com/jupyterlite/jupyterlite/issues/148#issuecomment-863434415)?



The scope for now for this PR would be to have basic support for the ephemeral consoles just like in lab. But the side-by-side text editor + console output could be implemented as a federated extension to start with maybe?

**Comment by jtpio** [comment]
This should also fix https://github.com/jupyterlab/retrolab/issues/104 with notebook - console interactions working across browser tabs:

https://user-images.githubusercontent.com/591645/131314806-104b4284-57fc-4410-86ba-aae6488a46be.mp4

**Comment by jtpio** [comment]
Maybe it could make sense to add the console favicon to Jupyter Server directly: https://github.com/jupyter-server/jupyter_server/tree/master/jupyter_server/static/favicons

console-icon

**Comment by jtpio** [comment]
> But the side-by-side text editor + console output could be implemented as a federated extension to start with maybe?

Or maybe something to do upstream in JupyterLab directly. Similar to https://github.com/jupyterlab/jupyterlab/pull/10648

**Comment by jtpio** [comment]
Seems to be working find on Binder, including the console favicon:

https://user-images.githubusercontent.com/591645/131338813-b6731215-be62-4422-9fdf-f6c500d11cbd.mp4

**Comment by jtpio** [comment]
Sounds like this it would be a great upstream feature to have.

**Pull request merged**
