### PR TITLE
Update to the `@jupyterlab` 3.2.6 packages

### LINKED ISSUE #300: Double slash in console URL
## Description

Not sure this is a bug, but it looks like the console URL now has a double slash, e.g.:
```
http://localhost:8888/retro/consoles//console-1-33a9d4ee-3873-4611-9edd-c1ff7afee29e
```

## Reproduce

1. Click "New Console"
2. See the URL in the opened window.

## Expected behavior

I wouldn't expect to see a double slash.

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Firefox 94.0
- RetroLab version: 0.3.13

### PR DESCRIPTION
**Pull request by jtpio**
Grab the latest fixes from the `3.2.6` release of JupyterLab: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.2.6

Fixes #300

### CODE REVIEW

**Comment by jtpio** [comment]
cc @davidbrochart this fixes the extra forward slash mentioned in #300:

image

**Comment by jtpio** [comment]
Visual regression failure seems legit, with a missing file browser icon:

image

Most likely related to https://github.com/jupyterlab/jupyterlab/pull/11758

**Comment by davidbrochart** [comment]
> cc @davidbrochart this fixes the extra forward slash mentioned in #300 

Great!

**Comment by jtpio** [comment]
CI all green now.

**Comment by jtpio** [comment]
Released in `0.3.16`: https://github.com/jupyterlab/retrolab/releases/tag/v0.3.16

**Pull request merged**
